on:
  push:
    branches:
      - main
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2

      - name: Clone and rename env file
        run: cp env.production .env

      - name: Install Vendors
        run: composer install

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: 68.178.148.226
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
